@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 15 12:21:07 +0100 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim TB_SPI_MS_time_impl -key {Post-Implementation:sim_1:Timing:TB_SPI_MS} -tclbatch TB_SPI_MS.tcl -view C:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/TB_SPI_MS_behav.wcfg -log simulate.log"
call xsim  TB_SPI_MS_time_impl -key {Post-Implementation:sim_1:Timing:TB_SPI_MS} -tclbatch TB_SPI_MS.tcl -view C:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/TB_SPI_MS_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
