# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/ip/FIFO_single_channel/FIFO_single_channel.xci
# IP: The module: 'FIFO_single_channel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/ip/FIFO_single_channel/FIFO_single_channel.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_single_channel'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/ip/FIFO_single_channel/FIFO_single_channel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_single_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/ip/FIFO_single_channel/FIFO_single_channel.xci
# IP: The module: 'FIFO_single_channel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/ip/FIFO_single_channel/FIFO_single_channel.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_single_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/ip/FIFO_single_channel/FIFO_single_channel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_single_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
