# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TOP.xdc

# Block Designs: bd/TOP_block/TOP_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block || ORIG_REF_NAME==TOP_block} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_axi_bram_ctrl_0_0/TOP_block_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_axi_bram_ctrl_0_0 || ORIG_REF_NAME==TOP_block_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_axi_dma_0_0/TOP_block_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_axi_dma_0_0 || ORIG_REF_NAME==TOP_block_axi_dma_0_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_axi_interconnect_0_0/TOP_block_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_axi_interconnect_0_0 || ORIG_REF_NAME==TOP_block_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_axi_uartlite_1_0/TOP_block_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_axi_uartlite_1_0 || ORIG_REF_NAME==TOP_block_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_blk_mem_gen_0_0/TOP_block_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_blk_mem_gen_0_0 || ORIG_REF_NAME==TOP_block_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_processing_system7_0_0/TOP_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_processing_system7_0_0 || ORIG_REF_NAME==TOP_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_ps7_0_axi_periph_0/TOP_block_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==TOP_block_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_xbar_0/TOP_block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_xbar_0 || ORIG_REF_NAME==TOP_block_xbar_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_rst_ps7_0_200M_0 || ORIG_REF_NAME==TOP_block_rst_ps7_0_200M_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_axis_data_fifo_0_1/TOP_block_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_axis_data_fifo_0_1 || ORIG_REF_NAME==TOP_block_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_axi_bram_ctrl_1_6/TOP_block_axi_bram_ctrl_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_axi_bram_ctrl_1_6 || ORIG_REF_NAME==TOP_block_axi_bram_ctrl_1_6} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_auto_pc_0/TOP_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_auto_pc_0 || ORIG_REF_NAME==TOP_block_auto_pc_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_auto_us_0/TOP_block_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_auto_us_0 || ORIG_REF_NAME==TOP_block_auto_us_0} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_auto_pc_4/TOP_block_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_auto_pc_4 || ORIG_REF_NAME==TOP_block_auto_pc_4} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_auto_pc_1/TOP_block_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_auto_pc_1 || ORIG_REF_NAME==TOP_block_auto_pc_1} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_auto_pc_2/TOP_block_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_auto_pc_2 || ORIG_REF_NAME==TOP_block_auto_pc_2} -quiet] -quiet

# IP: bd/TOP_block/ip/TOP_block_auto_pc_3/TOP_block_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_block_auto_pc_3 || ORIG_REF_NAME==TOP_block_auto_pc_3} -quiet] -quiet

# XDC: bd/TOP_block/TOP_block_ooc.xdc
