# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_auto_pc_3/TOP_block_auto_pc_3.xci
# IP: The module: 'TOP_block_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_auto_pc_3/TOP_block_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_auto_pc_3/TOP_block_auto_pc_3.xci
# IP: The module: 'TOP_block_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alexa/OneDrive/Desktop/Vivado_projects/mPMT_DAQ/mPMT_DAQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_auto_pc_3/TOP_block_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
